### ISSUE TITLE
npx create-next-app -e cms-makeswift makeswift-test and cd makeswift-test & npm run dev produces an error

### ISSUE THREAD

**Issue by milaabl** [makeswift/makeswift#112]
I haven't made any edits to the code yet, just a starter project.

I have created an "Index" page on my Makeswift project dashboard, set its path to "home". It should be at "http://localhost:3000/home" as the helper indicates below the page path field.

I have added the secret key to my .env.local.example as described in docs, but when I access the http://localhost:3000/home it says:

Server Error
TypeError: Only absolute URLs are supported

Console output is:

TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (D:\makeswift\makeswift-test\node_modules\next\dist\compiled\node-fetch\index.js:1:63538)
    at D:\makeswift\makeswift-test\node_modules\next\dist\compiled\node-fetch\index.js:1:65069
    at new Promise (<anonymous>)
    at Function.fetch [as default] (D:\makeswift\makeswift-test\node_modules\next\dist\compiled\node-fetch\index.js:1:65003)
    at fetchWithAgent (D:\makeswift\makeswift-test\node_modules\next\dist\server\node-polyfill-fetch.js:53:39)
    at getStaticProps (D:\makeswift\makeswift-test\node_modules\@makeswift\runtime\dist\next.cjs.js:152:21)
    at Object.renderToHTML (D:\makeswift\makeswift-test\node_modules\next\dist\server\render.js:451:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doRender (D:\makeswift\makeswift-test\node_modules\next\dist\server\base-server.js:912:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (D:\makeswift\makeswift-test\node_modules\next\dist\server\base-server.js:1017:28) {
  page: '/[[...path]]'
}

My OS is WIndows 10

**Comment by migueloller** [comment]
@milaabl, the environment variables should be added to `.env.local`, so make sure to rename `.env.local.example` to `.env.local` 😄

**Comment by milaabl** [comment]
@migueloller, yes, that solved the issue! :)
