### ISSUE TITLE
I can't deploy in Vercel / Metamask connection doesn't work

### ISSUE THREAD

**Issue by vonvanzu** [makeswift/makeswift#667]
Previously the first time I made the deployment to test and everything worked fine, but then I erase something, and suddenly it shows error.

So I erase everything and deploy it again. But this time the URL show 404 error and the Metamask bottom doesn't work properly.

https://www.loom.com/share/fa327d44871249f5b3f257baed9fc369?sid=05a43ab8-324d-4036-bdb1-2c0f42f25e14

I erase everything again, and try to do it in the terminal too, but now the process is stuck and not deploying anything at all.

https://www.loom.com/share/e6dc732fe5dd4a38950d3f0a56afa3fe?sid=9c9ac1fe-66f6-40d7-971a-f27a92afe456

Hope somebody help,
best regards,
LM

**Comment by migueloller** [comment]
The reason the page is showing a 404 is because the site must be published. Click the green publish button in the top right corner and select all the resources you want to go live with.

**Comment by vonvanzu** [comment]
Ok. But now I can not deploy the GitHub. Is stuck.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NFTRafflingdoteth** [comment]
was this ever resolved? I'm having the same problem with deployment.

**Comment by NFTRafflingdoteth** [comment]
![errormessage](https://github.com/makeswift/makeswift/assets/159603056/c82b8c79-5dee-4785-8dfd-2b2c3f6a74e3)

**Comment by vonvanzu** [comment]
[17:09:14.401] Running build in Washington, D.C., USA (East) – iad1
[17:09:14.553] Cloning github.com/vonvanzu/makeswift-thirdweb-example (Branch: main, Commit: d2b36df)
[17:09:18.177] Previous build cache not available
[17:09:18.256] Cloning completed: 3.702s
[17:09:18.513] Running "vercel build"
[17:09:18.997] Vercel CLI 33.5.0
[17:09:19.364] Installing dependencies...
[17:09:19.697] yarn install v1.22.17
[17:09:19.724] info No lockfile found.
[17:09:19.731] [1/4] Resolving packages...
[17:09:33.908] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @magic-ext/connect@6.7.2: Connect extension has been merged to magic-sdk, please download the latest magic-sdk to unlock more features
[17:09:33.996] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @safe-global/safe-ethers-lib@1.9.4: WARNING: This package is now bundled in @safe-global/protocol-kit. Please, follow the migration guide https://docs.safe.global/safe-core-aa-sdk/protocol-kit/reference/v1
[17:09:34.081] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @safe-global/safe-core-sdk@3.3.5: WARNING: This project has been renamed to @safe-global/protocol-kit. Please, follow the migration guide https://docs.safe.global/safe-core-aa-sdk/protocol-kit/reference/v1
[17:09:34.143] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @safe-global/safe-ethers-adapters > @safe-global/safe-core-sdk@3.3.5: WARNING: This project has been renamed to @safe-global/protocol-kit. Please, follow the migration guide https://docs.safe.global/safe-core-aa-sdk/protocol-kit/reference/v1
[17:09:35.638] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @blocto/sdk > eip1193-provider@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[17:09:36.449] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @safe-global/safe-core-sdk > zksync-web3@0.14.4: This package has been deprecated in favor of zksync-ethers@5.0.0
[17:09:39.289] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @blocto/sdk > eip1193-provider > @json-rpc-tools/provider@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[17:09:41.270] warning @thirdweb-dev/react > @thirdweb-dev/react-core > @thirdweb-dev/storage > cid-tool > cids@1.1.9: This module has been superseded by the multiformats module
[17:09:41.316] warning @thirdweb-dev/react > @thirdweb-dev/react-core > @thirdweb-dev/storage > cid-tool > multibase@4.0.6: This module has been superseded by the multiformats module
[17:09:41.317] warning @thirdweb-dev/react > @thirdweb-dev/react-core > @thirdweb-dev/storage > cid-tool > cids > multibase@4.0.6: This module has been superseded by the multiformats module
[17:09:41.546] warning @thirdweb-dev/react > @thirdweb-dev/react-core > @thirdweb-dev/storage > cid-tool > multihashes > multibase@4.0.6: This module has been superseded by the multiformats module
[17:09:41.824] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @blocto/sdk > eip1193-provider > @json-rpc-tools/provider > @json-rpc-tools/utils@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[17:09:42.270] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @walletconnect/modal > @walletconnect/modal-ui > motion > @motionone/vue@10.16.4: Motion One for Vue is deprecated. Use Oku Motion instead https://oku-ui.com/motion
[17:09:42.568] warning @thirdweb-dev/react > @thirdweb-dev/react-core > @thirdweb-dev/storage > cid-tool > cids > multicodec@3.2.1: This module has been superseded by the multiformats module
[17:09:42.941] warning @thirdweb-dev/react > @thirdweb-dev/wallets > @blocto/sdk > eip1193-provider > @json-rpc-tools/provider > @json-rpc-tools/utils > @json-rpc-tools/types@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[17:09:47.491] [2/4] Fetching packages...
[17:10:37.929] warning abitype@0.2.5: The engine "pnpm" appears to be invalid.
[17:10:37.941] [3/4] Linking dependencies...
[17:10:37.942] warning " > @chakra-ui/menu@2.2.1" has unmet peer dependency "@chakra-ui/system@>=2.0.0".
[17:10:37.953] warning "@thirdweb-dev/react > @thirdweb-dev/wallets@1.3.5" has unmet peer dependency "ethers-gcp-kms-signer@^1.1.6".
[17:10:37.955] warning "@thirdweb-dev/react > @thirdweb-dev/wallets > @magic-sdk/provider@13.6.2" has unmet peer dependency "localforage@^1.7.4".
[17:10:37.955] warning "@thirdweb-dev/react > @thirdweb-dev/wallets > @safe-global/safe-ethers-adapters@0.1.0-alpha.17" has unmet peer dependency "@ethersproject/abstract-provider@^5.7.0".
[17:10:37.955] warning "@thirdweb-dev/react > @thirdweb-dev/wallets > @safe-global/safe-ethers-adapters@0.1.0-alpha.17" has unmet peer dependency "@ethersproject/abstract-signer@^5.7.0".
[17:10:37.956] warning "@thirdweb-dev/react > @thirdweb-dev/wallets > @safe-global/safe-ethers-adapters@0.1.0-alpha.17" has unmet peer dependency "@ethersproject/bignumber@^5.7.0".
[17:10:37.956] warning "@thirdweb-dev/react > @thirdweb-dev/wallets > @safe-global/safe-ethers-adapters@0.1.0-alpha.17" has unmet peer dependency "@ethersproject/properties@^5.7.0".
[17:11:21.101] [4/4] Building fresh packages...
[17:11:25.360] success Saved lockfile.
[17:11:25.366] Done in 125.67s.
[17:11:25.457] Detected Next.js version: 13.5.6
[17:11:25.459] Running "yarn run build"
[17:11:25.641] yarn run v1.22.17
[17:11:25.669] $ next build
[17:11:26.396] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[17:11:26.396] This information is used to shape Next.js' roadmap and prioritize features.
[17:11:26.397] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[17:11:26.397] https://nextjs.org/telemetry
[17:11:26.397] 
[17:11:26.487]    Linting and checking validity of types ...
[17:11:38.797]    Creating an optimized production build ...
[17:12:14.514]  ✓ Compiled successfully
[17:12:14.517]    Collecting page data ...
[17:12:16.388] Error: "MAKESWIFT_SITE_API_KEY" env var is not defined.
[17:12:16.388]     at /vercel/path0/.next/server/pages/[[...path]].js:1:23280
[17:12:16.388]     at getConfig (/vercel/path0/.next/server/pages/[[...path]].js:1:23329)
[17:12:16.388]     at getStaticPaths (/vercel/path0/.next/server/pages/[[...path]].js:1:24831)
[17:12:16.388]     at buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:733:39)
[17:12:16.389]     at /vercel/path0/node_modules/next/dist/build/utils.js:1140:116
[17:12:16.389]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:105:20)
[17:12:16.394] 
[17:12:16.394] > Build error occurred
[17:12:16.396] Error: Failed to collect page data for /[[...path]]
[17:12:16.397]     at /vercel/path0/node_modules/next/dist/build/utils.js:1171:15 {
[17:12:16.397]   type: 'Error'
[17:12:16.397] }
[17:12:16.510] error Command failed with exit code 1.
[17:12:16.511] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[17:12:16.535] Error: Command "yarn run build" exited with 1
[17:12:17.296] 
![Screen Shot 2024-02-10 at 17 16 21](https://github.com/makeswift/makeswift/assets/65814250/15f611e1-7ee4-4202-891b-980daab3f31a)
![Screen Shot 2024-02-10 at 17 16 36](https://github.com/makeswift/makeswift/assets/65814250/5ee46283-4bc7-47b7-a225-7fff1b7d6836)

**Comment by vonvanzu** [comment]
Thank you. Now is supposed to be installed BUT it shows an error with the DOMAIN: ¨Your most recent Production Deployment has failed and your Domain couldn't be assigned. Your domain will be assigned on your next successful Production Deployment¨. What happened? I have to deploy it again?. Best regards.
![Screen Shot 2024-02-12 at 19 48 40](https://github.com/makeswift/makeswift/assets/65814250/d5602530-8e95-4458-8f4e-141570a0e995)
![Screen Shot 2024-02-12 at 19 49 36](https://github.com/makeswift/makeswift/assets/65814250/15cf1a44-a562-4649-babb-751f200b2dc4)

**Comment by migueloller** [comment]
Yes. New environment variables are only applied after new deployments.
